package com.jgc.crm.settings.mapper;

import com.jgc.crm.settings.transaction.model.User;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Oct 06 15:33:32 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Oct 06 15:33:32 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Oct 06 15:33:32 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Oct 06 15:33:32 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Oct 06 15:33:32 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Oct 06 15:33:32 CST 2022
     */
    int updateByPrimaryKey(User record);
    /**
     * 根据用户账号和密码查询
     */
    User selectUserByLoginActAndLoginPwd(Map<String,Object> map);

    /**
     * 查询全部用户
     * @return
     */
    List<User> queryUsers();
}